typography_spectrum: 0
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7595688863657415
  lightness: 0.7348334449343383
  saturation: 0.8108768167439848
  rhythmicContrast: 0.18322767945937812
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75286
analytics:
  google: null
  facebook: null
  twitter: null
name: InstallSystem
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: >-
      I am typing my text here in drafts. for a specific "Post". Apparently. Can
      I change the font? Can I create paragraphs and lists? What? no new line
      what kind of a weird system is this?!
    id: 675da748-0820-48c7-a368-51f97893ef18
    type: content
favicon: null
title: Apparently the Site Title goes here
description: Tagline goes here
purpose: []
